### ISSUE TITLE
hyperline not showing up

### ISSUE THREAD

**Issue by linkurzweg** [NickTikhonov/hyperterm-hyperline#50]
I installed hyperline and am using the default configuration from the readme, but the line is not showing up, there is no information displayed (I'm using a 2015 MacBook Pro with Mac OS Sierra 10.12 and Hyper 0.8.3). Am I doing something wrong?

**Comment by timneutkens** [comment]
It's not you. We've fixed this already. Haven't released it yet though. Haven't been able to reach @NickTikhonov. For now you can install hyperline locally in `~/.hyper_plugins/local/hyperline`.
Or use `hpm` to install it with `hpm fork hyperline` https://github.com/zeit/hpm

**Comment by linkurzweg** [comment]
Thanks for the info, I will do that!

**Comment by timneutkens** [comment]
I'll close this 👍

**Comment by ajma** [comment]
hpm fork hyperline https://github.com/zeit/hpm didn't help my install. Still don't see hyperline

**Comment by ajma** [comment]
I just installed it locally into /.hyper_plugins/local/hyperline by cloning the repo and then building it.
